# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 18:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sistema', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha presentaci\xf3n candidatura')),
                ('tipo', models.IntegerField(verbose_name='Convocatoria (0=No confirmada')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('n_socio', models.CharField(blank=True, max_length=20, null=True, verbose_name='N\xba de socio/a')),
                ('localidad', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha antig\xfcedad')),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True, verbose_name='Breve descripci\xf3n -m\xe1ximo 150 caracteres-')),
                ('cv', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Curr\xedculum profesional -m\xe1ximo 1000 caracteres-')),
                ('vinculacion', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Vinculaci\xf3n con Greenpeace -m\xe1ximo 1000 caracteres-')),
                ('motivacion', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Motivaci\xf3n para presentar la candidatura -m\xe1ximo 1000 caracteres-')),
                ('campanha', models.TextField(blank=True, max_length=150, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='\xbfQu\xe9 campa\xf1a crees que le falta a Greenpeace Espa\xf1a y por qu\xe9? -m\xe1ximo 150 caracteres-')),
                ('dni', models.FileField(upload_to=b'%Y/%m/%d', verbose_name='Copia del DNI/ Pasaporte/ Tarjeta de residente')),
                ('dni_presenta', models.FileField(blank=True, null=True, upload_to=b'%Y/%m/%d', verbose_name='Miembro del Consejo que presenta al candidato/a: Copia del DNI/ Pasaporte/ Tarjeta de residente')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=b'%Y/%m/%d', verbose_name='Foto -m\xe1ximo 200kB-')),
                ('correo_e', models.EmailField(max_length=254, verbose_name='Correo electr\xf3nico -para facilitar a la comisi\xf3n electoral la resoluci\xf3n de errores-')),
                ('participacion_activa', models.BooleanField(verbose_name='Compromiso de participaci\xf3n activa: Al presentar esta candidatura adquiero el compromiso, en caso de resultar elegido/a, de participar activamente en las labores que el Consejo tiene se\xf1aladas o se se\xf1alen.')),
                ('veracidad', models.BooleanField(verbose_name='Doy fe de la veracidad de los datos')),
                ('mayor_edad', models.NullBooleanField()),
                ('antiguedad_3a', models.NullBooleanField(verbose_name='Antig\xfcedad > 3 a\xf1os')),
                ('valida_sistema', models.NullBooleanField(verbose_name=b'Comprobada por el sistema')),
                ('circunscripcion_correcta', models.NullBooleanField(verbose_name='Circunscripci\xf3n correcta')),
                ('valida', models.NullBooleanField(verbose_name='Validada por la Comisi\xf3n Electoral')),
                ('comentarios', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('alegaciones', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('en_el_consejo', models.BooleanField(verbose_name='Consejero en la actualidad')),
                ('frecuencia_acceso', models.IntegerField(blank=True, choices=[(1, 'Diariamente'), (2, 'Semanalmente'), (3, 'Mensualmente')], null=True, verbose_name='Con qu\xe9 frecuencia aproximada accedes a los medios de conversaci\xf3n y debate del Consejo')),
                ('aportacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Valora, de uno a diez, tu grado de satisfacci\xf3n con tu aportaci\xf3n al Consejo')),
            ],
            options={
                'ordering': ('fecha_alta', 'apellidos'),
            },
        ),
        migrations.CreateModel(
            name='Consejero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('activo', models.BooleanField()),
                ('fecha_voto', models.DateTimeField(blank=True, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('circunscripcion_voto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circunscripcion_voto_25', to='comun.Circunscripcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('apellidos', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('voto_nulo', models.BooleanField()),
                ('voto_blanco', models.BooleanField()),
                ('circunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comun.Circunscripcion')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_register_ballot', 'Can register a ballot'),),
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
            ],
            options={
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuento.Candidato')),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuento.Papeleta')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='asistencia',
            field=models.ManyToManyField(blank=True, to='recuento.Reunion', verbose_name='Se\xf1ala las asambleas y encuentros a las que hayas asistido en tu \xfaltimo mandato'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='circunscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comun.Circunscripcion', verbose_name='Circunscripci\xf3n'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='recuento.Grupo', verbose_name='Indica en qu\xe9 grupos has participado activamente'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='presenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recuento.Consejero', verbose_name='Miembro del Consejo que presenta al candidato/a'),
        ),
    ]
